
image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf &&
      nix-shell &&
      de-preload

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addBadge: true
    addLabel: true

vscode:
  extensions:
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - scala-lang.scala
    - ms-azuretools.vscode-docker
    - jnoortheen.nix-ide
